### ISSUE TITLE
Bridge Page Styling: Move boxes on top of one another

### ISSUE THREAD

**Issue by garyghayrat** [ScopeLift/l2-flexible-voting-frontend#112]
this is certainly an issue. I wonder if it's better dealt with in a different PR that sorta restyles each box and maybe reorients them on top of one another. i have a light preference to keep this PR limited to just the styling of L2 tokens.

_Originally posted by @wildmolasses in https://github.com/ScopeLift/l2-flexible-voting-frontend/pull/107#discussion_r1386435575_

**Comment by wildmolasses** [comment]
Closed by #123
