### ISSUE TITLE
Change dao url parameter to a string

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/l2-flexible-voting-frontend#115]
#### Description

- Right now we use internal IDs and we may potentially want to use DAO names.

_Originally posted by @wildmolasses in https://github.com/ScopeLift/l2-flexible-voting-frontend/pull/106#discussion_r1386411172_

**Comment by wildmolasses** [comment]
thanks for creating the issue. To follow up on your comment:

> My one worry with that scheme is we can run into future problems if names aren't unique. Although, I don't see that being an issue anytime soon. We could do /[id]/[name]/bridge?

I think we can ignore the non-unique names thing. At worst we could just do what tally does, aka a `flexible-voting-6` type of thing. At best, on the other hand, we get a nice url without any "junk" in it.
