### ISSUE TITLE
Initial Version of Delegation / Voting Weight Page

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting-frontend#5]
The initial version of the "Delegate" tab should include:

- [x] Show your L2 token balance
- [x] Show who your L2 tokens are currently delegated to (will default to yourself)
- [x] Show your current total voting weight (i.e. delegated power to your address)
- [x] Enable the user to set their delegate

Possible stretch:

- [ ] In a sub-section of the UI, also show L1 token balance / voting weight and link to other platform(s) to enable setting/updating this

**Comment by alexkeating** [comment]
I am going to pull the stretch into a separate issue.

**Comment by alexkeating** [comment]
We will need a subgraph to figure out who the tokens are currently delegated to.
