### ISSUE TITLE
Bridge Page: Decide how to handle various error states on the bridge page

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting-frontend#79]
Examples:

* User needs to switch network
* Still needs to set their allowance

<img width="758" alt="Screen Shot 2023-10-25 at 4 26 41 PM" src="https://github.com/ScopeLift/l2-flexible-voting-frontend/assets/1479802/f8726dd2-ab82-43b8-b392-30ec6e287efb">

<img width="722" alt="Screen Shot 2023-10-30 at 9 54 27 PM" src="https://github.com/ScopeLift/l2-flexible-voting-frontend/assets/1479802/8a290455-b405-4eee-9d00-8c42926c97f0">

Possible approach is to disable the simulation until the proper criteria are met (network, allowance, etc..?) and therefore avoid showing or having to suppress error messages that are not useful.

**Comment by wildmolasses** [comment]
Related to #70

**Comment by wildmolasses** [comment]
Related to discussion in #90
